# raise:  lançando exceções

print(8/0)
raise ValueError("Deu Error") # "levanta" o error e mostra na tela
print(1245)